# Travis continuous integration system configuration file.
# Read more at: http://docs.travis-ci.com/user/customizing-the-build/

sudo: required
dist: xenial
language: node_js
node_js: 11.6.0

git:
  depth: 250
  quiet: true

cache:
  directories:
    - .cached_tools
    - node_modules

before_install:
  - export GOPATH=$TRAVIS_BUILD_DIR/.tmp
  - mkdir -p $TRAVIS_BUILD_DIR/.tmp/src/github.com/kubernetes/dashboard/src/app
  - cp -r $TRAVIS_BUILD_DIR/src/app/backend $TRAVIS_BUILD_DIR/.tmp/src/github.com/kubernetes/dashboard/src/app
  - ln -s $TRAVIS_BUILD_DIR/vendor $TRAVIS_BUILD_DIR/.tmp/src/github.com/kubernetes/dashboard/src/app/backend/vendor

before_script:
  - eval "$(gimme 1.11.4)"
  - docker --version

jobs:
  include:
    - stage: test
      script: npm run check
    - script: npm run test:coverage
      after_success:
        - rm -rf $TRAVIS_BUILD_DIR/.tmp
        - bash <(curl -s https://codecov.io/bash)
    - addons:
        sauce_connect: true
      script:
        - npm run cluster
        - npm run test:e2e
      env:
        - KUBE_DASHBOARD_KUBECONFIG=$HOME/.kube/config
    - stage: deploy
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - npm run docker:push:head:cross

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
