# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Travis continuous integration system configuration file. 
#
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

# Explicitly set the environment to be container-based. This makes the builds faster.
sudo: true
# Cache downloaded Node.JS modules & Bower frontend dependencies for faster builds.
cache:
  directories:
    - node_modules
    - bower_components
# Use Node.js as primary language because Gulp is the build system used in the project.
language: node_js

services:
  - docker

before_script:
  # Prepare environment for the Chrome browser.
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Install frontend dependencies to be able to build the project.
  - ./node_modules/.bin/bower install

  # Set up Go environment for build.
  - export GOPATH=$HOME/.gopath
  # Download godep tool and make add it to PATH environment variable.
  - go get github.com/tools/godep
  - export PATH=$PATH:$GOPATH/bin
  - curl -fsSL https://github.com/coreos/etcd/releases/download/v2.2.1/etcd-v2.2.1-linux-amd64.tar.gz | tar xzf -
  - ln -fns etcd-v2.2.1-linux-amd64 etcd
  - export PATH=./etcd:$PATH
  - etcd --version
  - go version
#script: ./node_modules/.bin/gulp check
script: ./node_modules/.bin/gulp create-cluster
after_script:
  - cd ./.tmp/kubernetes/; make quick-release
