[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/api"
  version="kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/client-go"
  version="kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/heapster"
  version = "1.5.4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "2.7.0"

[[override]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "golang.org/x/text"
  branch = "master"

[[constraint]]
  name = "gopkg.in/igm/sockjs-go.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.9.6"

[[override]]
  name = "github.com/square/go-jose"
  version = "2.2.2"
