# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"
services:
  web:
    build:
      context: ../..
      dockerfile: modules/web/Dockerfile
      args:
        - BUILDPLATFORM=${OS:?}/${ARCH:?}
        - BUILDARCH=${ARCH:?}
    command:
      --locale-config=/public/locale_conf.json
      --auto-generate-certificates
      --system-banner="${SYSTEM_BANNER:?}"
      --system-banner-severity=${SYSTEM_BANNER_SEVERITY:?}
    tmpfs:
      - /tmp
  api:
    build:
      context: ../..
      dockerfile: modules/api/Dockerfile
      args:
        - BUILDPLATFORM=${OS:?}/${ARCH:?}
        - BUILDARCH=${ARCH:?}
    command:
      --kubeconfig=${KUBECONFIG:?}
      --auto-generate-certificates
      --enable-skip-login=${ENABLE_SKIP_LOGIN:?}
      --sidecar-host=${SIDECAR_HOST:?}
      --token-ttl=${TOKEN_TTL:?}
    volumes:
      - ${KUBECONFIG:?}:${KUBECONFIG:?}
    tmpfs:
      - /tmp
    ports:
      - "9001:9001"
  scraper:
    image: kubernetesui/metrics-scraper:v1.0.8
    command:
      # TODO: move metrics args to some overridable env variables
      --kubeconfig=${KUBECONFIG:?}
      --metric-resolution=5s
      --metric-duration=10m
    volumes:
      - ${KUBECONFIG:?}:${KUBECONFIG:?}
    tmpfs:
      - /tmp
  gateway:
    build:
      context: ../..
      dockerfile: hack/gateway/Dockerfile
    ports:
      - "4443:4443"

networks:
  kubernetes-dashboard:
