# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 1'
permissions:
  contents: read
jobs:

  license-check:
    name: License check
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: apache/skywalking-eyes@main

  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go', 'typescript' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v2
      - uses: github/codeql-action/analyze@v2

  dependency-review:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Dependency review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: critical

  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    env:
      NG_CLI_ANALYTICS: ci
      GOPROXY: "https://proxy.golang.org"
      NODE_OPTIONS: "--max-old-space-size=8192"
      TERM: xterm
    steps:
      - uses: helm/kind-action@v1.4.0
        with:
          version: v0.15.0
          kubectl_version: v1.25.1
          cluster_name: k8s-cluster-ci
      - run: |
          docker run --net=host -d k8s.gcr.io/heapster-amd64:v1.5.4 \
             --heapster-port=8082 \
             --source=kubernetes:http://127.0.0.1:8080?inClusterConfig=false&auth=""
      - run: kind get kubeconfig --name="k8s-cluster-ci" > ${HOME}/.kube/config
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: yarn
        working-directory: modules/web
      - run: node hack/version.mjs
        working-directory: modules/web
      - run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          make serve &
      - run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          yarn cypress
        working-directory: modules/web
