# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Continuous Integration - Code

on:
  push:
    branches: [ master ]
    ignore-paths:
      - '**/*.md'
      - 'aio/deploy/**'
      - 'aio/test-resources/**'
      - 'docs/**'
      - '.github/workflows/cd-helm-workflow.yml'
      - '.github/workflows/cd-workflow.yml'
  pull_request:
    branches: [ master ]
    ignore-paths:
      - '**/*.md'
      - 'aio/deploy/**'
      - 'aio/test-resources/**'
      - 'docs/**'
      - '.github/workflows/cd-helm-workflow.yml'
      - '.github/workflows/cd-workflow.yml'

permissions:
  contents: read

jobs:
  check:
    name: Static Check
    runs-on: ubuntu-latest
    env:
      NG_CLI_ANALYTICS: ci
      GO111MODULE: on
      GOPROXY: "https://proxy.golang.org"
      NODE_OPTIONS: "--max-old-space-size=8192"
      TERM: xterm
    steps:
      - name: Setup Environment
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2
        with:
          go-version: 1.17.0

      - name: Setup NodeJS
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v2.1.2
        with:
          node-version: 16.14.2

      - name: Cache Node Modules
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        shell: bash
        run: |
          [ ! -d "node_modules" ] && npm ci || node aio/scripts/version.mjs && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1; } && go mod download

      - name: Check Code
        shell: bash
        run: |
          export GOPATH=$(go env GOPATH)/bin
          npm run check

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      NG_CLI_ANALYTICS: ci
      GO111MODULE: on
      GOPROXY: "https://proxy.golang.org"
      NODE_OPTIONS: "--max-old-space-size=8192"
      TERM: xterm

    steps:
      - name: Setup Environment
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2
        with:
          go-version: 1.17.0

      - name: Setup NodeJS
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v2.1.2
        with:
          node-version: 16.14.2

      - name: Cache Node Modules
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        shell: bash
        run: |
          export GOPATH=$(go env GOPATH)/bin
          [ ! -d "node_modules" ] && npm ci || node aio/scripts/version.mjs && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1; } && go mod download

      - name: Run Frontend Unit Tests
        run: make coverage-frontend

      - name: Run Backend Unit Tests
        run: make coverage-backend

      - name: Cleanup & Upload Coverage
        shell: bash
        run: |
          make clean
          bash <(curl -s https://codecov.io/bash) -c -K || echo "Codecov upload failed"

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      NG_CLI_ANALYTICS: ci
      GO111MODULE: on
      GOPROXY: "https://proxy.golang.org"
      NODE_OPTIONS: "--max-old-space-size=8192"
      TERM: xterm

    steps:
      - name: Setup Environment
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
        with:
          fetch-depth: 0

      # Increase watchers system limit
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Setup Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2
        with:
          go-version: 1.17.0

      - name: Setup NodeJS
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v2.1.2
        with:
          node-version: 16.14.2

      - name: Cache Node Modules
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        shell: bash
        run: |
          [ ! -d "node_modules" ] && npm ci && npm install cypress || node aio/scripts/version.mjs && command -v golangci-lint >/dev/null 2>&1 || { curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1; } && go mod download

      - name: Run E2E Tests
        run: make e2e
